### ISSUE TITLE
PHP 7.4 problem

### ISSUE THREAD

**Issue by NgLam2911** [NetherGamesMC/noiselib#3]
This extension cant run on PHP 7.4, it can only run on php 8+

**Comment by larryTheCoder** [comment]
The extension wasn't developed and tested for 7.4, but we will try to fix the problem and run some tests for PHP 7.4 and possibly as lower to PHP 7.2.

**Comment by NgLam2911** [comment]
> The extension wasn't developed and tested for 7.4, but we will try to fix the problem and run some tests for PHP 7.4 and possibly as lower to PHP 7.2.

I think php 7.3 is isnt neccessary, because PocketMine-MP 4.0.0 is requied PHP 7.4+

**Comment by larryTheCoder** [comment]
Well you are right, PHP 7.3 is not necessary for PM4, but the extension is able to run on PHP 7.3 since the API is the same as 7.4. It also allows plugin developers to use this extension for PM3 at the same time. The 2.0 branch will only be available only for PM4—this is what I am currently working on right now.

**Comment by larryTheCoder** [comment]
I tested the current build and it now compiles and runs correctly as it should. I will be closing this issue, if there's any problem occurs (i.e segmentation fault, wrong behaviors), feel free to open another issue.
